NEWSAPI_KEY: ${oc.env:NEWSAPI_KEY}
NEWSDATAIO_KEY: ${oc.env:NEWSDATAIO_KEY}
NEWS_TOPIC: ${oc.env:NEWS_TOPIC}
ARTICLES_BATCH_SIZE: 10
FETCH_WAIT_WINDOW: 1800
EMBEDDING_MODEL_ID: "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_MODEL_MAX_INPUT_LENGTH: 384
EMBEDDING_MODEL_DEVICE: "cpu"
VECTOR_DB_OUTPUT_COLLECTION_NAME: ${oc.env:VECTOR_DB_OUTPUT_COLLECTION_NAME}
QDRANT_API_KEY: ${oc.env:QDRANT_API_KEY}
QDRANT_URL: ${oc.env:QDRANT_URL}
